services:
  - type: web
    name: vhu-telegram-bot
    env: node
    plan: free
    buildCommand: apt-get update && apt-get install -y chromium-browser && npm install
    startCommand: node bot.js
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: VHU_EMAIL
        sync: false
      - key: VHU_PASSWORD
        sync: false
      - key: PUPPETEER_SKIP_DOWNLOAD
        value: "true"
